title:        Chandu
tagline:      'My thoughts on coding. '
description:  'A dumpyard for my thoughts on coding.'
url:          http://chandu.ca
version:      0.0.1
author:
  name:       'Chandu'
  email:      'chandra.vedantham@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
